stages:
  - build
  - test
  - deploy

include:
  - project: fabnum-minarm/igloo/gitlab-templates
    file: 
      - /proxy/licence-scanning.yml
      - /proxy/dependency-scanning.yml
      - /proxy/container-scanning.yml
      - /proxy/secret-scanning.yml
      - /proxy/sast.yml
      - /npm.auto.yml
      - /docker.auto.yml
      - /helm.yml
      - /helm.reviews.auto.yml
      - /helm.staging.auto.yml
      - /helm.production.auto.yml

variables:
  HELM_CHART: igloo-stable/nodejs
  HELM_ENV_VAR_VERSION: Version ${CI_COMMIT_REF_NAME} - ${CI_COMMIT_SHA} (job \#${CI_JOB_ID})

npm:test:
  image: node:lts-alpine
  services:
    - mongo:latest
  variables:
    MONGODB: "mongodb://mongo/stargate"
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  artifacts:
    reports:
      cobertura: coverage/clover.xml

deploy:review:
  variables:
    HOST: ${CI_ENVIRONMENT_SLUG}.api.${BASE_DOMAIN}
    HELM_INGRESS_HOST: $HOST
    HELM_NAME: backend-${CI_COMMIT_REF_SLUG}
    HELM_UPGRADE_EXTRA_ARGS: --set envVars.MONGODB="${HELM_ENV_VAR_MONGODB}${CI_COMMIT_REF_SLUG}"
  after_script:
    - kubectl logs -f job/${HELM_NAME}-nodejs || true
  environment:
    url: https://${CI_ENVIRONMENT_SLUG}.${BASE_DOMAIN}

deploy:review:uninstall:
  variables:
    HELM_NAME: backend-${CI_COMMIT_REF_SLUG}

deploy:staging:
  variables:
    HOST: api.${BASE_DOMAIN}
    HELM_INGRESS_HOST: $HOST
    HELM_NAME: backend
  after_script:
    - kubectl logs -f job/${HELM_NAME}-nodejs || true
  environment:
    url: https://${BASE_DOMAIN}

deploy:staging:uninstall:
  variables:
    HELM_NAME: backend

deploy:production:
  variables:
    HOST: api.${BASE_DOMAIN}
    HELM_INGRESS_HOST: $HOST
    HELM_NAME: backend
  environment:
    url: https://${BASE_DOMAIN}

deploy:production:uninstall:
  variables:
    HELM_NAME: backend

pages:
  extends: .igloo:npm:pages-docs
