stages:
  - build
  - test
  - deploy

include:
  - project: fabnum-minarm/igloo/gitlab-templates
    file: /proxy/licence-scanning.yml
  - project: fabnum-minarm/igloo/gitlab-templates
    file: /proxy/dependency-scanning.yml
  - project: fabnum-minarm/igloo/gitlab-templates
    file: /proxy/container-scanning.yml
  - project: fabnum-minarm/igloo/gitlab-templates
    file: /proxy/secret-scanning.yml
  - project: fabnum-minarm/igloo/gitlab-templates
    file: /proxy/sast.yml
  - project: fabnum-minarm/igloo/gitlab-templates
    file: /npm.auto.yml
  - project: fabnum-minarm/igloo/gitlab-templates
    file: /docker.auto.yml
  - project: fabnum-minarm/igloo/gitlab-templates
    file: /helm.yml
  - project: fabnum-minarm/igloo/gitlab-templates
    file: /helm.reviews.auto.yml
  - project: fabnum-minarm/igloo/gitlab-templates
    file: /helm.staging.auto.yml

variables:
  HELM_CHART: igloo-stable/nodejs
  HELM_ENV_VAR_VERSION: Version ${CI_COMMIT_REF_NAME} - ${CI_COMMIT_SHA} (job \#${CI_JOB_ID})

npm:test:
  services:
    - mongo:latest
  variables:
    MONGODB: "mongodb://mongo/stargate"

deploy:staging:
  variables:
    HOST: api.${BASE_DOMAIN}
    HELM_INGRESS_HOST: $HOST
    HELM_NAME: backend
  after_script:
    - kubectl logs -f job/${HELM_NAME}-nodejs || true
  environment:
    url: https://${BASE_DOMAIN}

deploy:staging:uninstall:
  variables:
    HELM_NAME: backend

deploy:review:
  variables:
    HOST: ${CI_ENVIRONMENT_SLUG}.api.${BASE_DOMAIN}
    HELM_INGRESS_HOST: $HOST
    HELM_NAME: backend-${CI_COMMIT_REF_SLUG}
    HELM_UPGRADE_EXTRA_ARGS: --set envVars.MONGODB="${HELM_ENV_VAR_MONGODB}${CI_COMMIT_REF_SLUG}"
  after_script:
    - kubectl logs -f job/${HELM_NAME}-nodejs || true
  environment:
    url: https://${CI_ENVIRONMENT_SLUG}.${BASE_DOMAIN}

deploy:review:uninstall:
  variables:
    HELM_NAME: backend-${CI_COMMIT_REF_SLUG}
