apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "node.fullname" . }}
  labels:
    {{- include "node.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "node.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ include "node.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MONGODB
              value: "{{ .Values.env.MONGODB }}"
            - name: VERSION
              value: "{{ .Values.env.VERSION }}"
            - name: MAIL__TRANSPORTER__HOST
              value: "{{ .Values.env.MAIL__TRANSPORTER__HOST }}"
            - name: MAIL__TRANSPORTER__PORT
              value: "{{ .Values.env.MAIL__TRANSPORTER__PORT }}"
            - name: MAIL__TRANSPORTER__AUTH__USER
              value: "{{ .Values.env.MAIL__TRANSPORTER__AUTH__USER }}"
            - name: MAIL__TRANSPORTER__AUTH__PASS
              value: "{{ .Values.env.MAIL__TRANSPORTER__AUTH__PASS }}"
            - name: MAIL__DEFAULT_FROM
              value: "{{ .Values.env.MAIL__DEFAULT_FROM }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.monitoring.exporter.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 25
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 25
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
