{{- if .Values.resetJob }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "node.fullname" . }}
  labels:
    {{- include "node.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "node.fullname" . }}
      labels:
        {{- include "node.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["run", "fixtures:clear"]
          env:
            - name: MONGODB
              value: "{{ .Values.env.MONGODB }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end}}
